In [13]:
from pathlib import Path
import pandas as pd
PROJECT_ROOT = Path.cwd().parent
KNOWLEDGE_BASE_DIR = PROJECT_ROOT / "data" / "knowledge_base"

print("Project root:", PROJECT_ROOT)
print("Knowledge base:", KNOWLEDGE_BASE_DIR)

Project root: d:\ai-customer-support-assistant
Knowledge base: d:\ai-customer-support-assistant\data\knowledge_base

In [2]:
files = sorted(KNOWLEDGE_BASE_DIR.glob("*.md"))

print(f"Number of documents: {len(files)}")

for file in files:
    print("-", file.name)

Number of documents: 6
- account.md
- billing.md
- payments.md
- refunds.md
- returns.md
- technical_support.md

In [3]:
for file in files:
    print("=" * 70)
    print(f"FILE: {file.name}")
    print("=" * 70)

    text = file.read_text(encoding="utf-8")

    print(text[:1000])
    print()

======================================================================
FILE: account.md
======================================================================
# Account Support

## Creating an Account

Customers can create an account by providing their email address and choosing a secure password. The email address should be valid and accessible because it may be required for account verification.

## Account Verification

If an account requires verification, customers should check their email for the verification message. They should also check their spam or junk folder if the message is not visible in the inbox.

## Forgot Password

Customers who forget their password should use the password reset option on the sign-in page. A password reset link will be sent to the registered email address.

## Password Reset Email Not Received

If the password reset email does not arrive, customers should check their spam or junk folder and confirm that they entered the correct email address. If the email is still not received, they should contact customer support.

## Change Account Email

Customers who need to change the email associated with their acc

======================================================================
FILE: billing.md
======================================================================
# Billing Support

## Billing Cycle

Customers are charged according to their selected billing plan. The billing date may vary depending on when the subscription was started.

## Unexpected Charge

If a customer notices an unexpected charge, they should review their billing history and verify whether the charge is related to an active subscription or recent purchase.

If the charge cannot be identified, the customer should contact support with the transaction details.

## Duplicate Charge

If a customer believes they were charged twice for the same transaction, they should check their payment history first. If two completed charges are present for the same purchase, they should contact support with the transaction details.

## Invoice

Customers can request or access their invoice through their account billing section. If an invoice is missing or contains incorrect information, they should contact customer support.

## Billing Information

Customers who need to update their billing inf

======================================================================
FILE: payments.md
======================================================================
# Payment Support

## Payment Failed

If a payment fails, customers should verify that their payment method has sufficient funds and that the billing information is correct.

Customers can try the payment again after checking their payment details. If the payment continues to fail, they should contact customer support.

## Payment Declined

A payment may be declined by the payment provider because of insufficient funds, incorrect payment information, or security restrictions.

Customers should verify their payment details and contact their bank or payment provider if necessary.

## Payment Pending

If a payment remains pending, customers should wait for the payment status to update. Customers should avoid submitting the same payment repeatedly while the original transaction is still pending.

If the payment remains pending for an extended period, they should contact customer support with the transaction details.

## Payment Reversed

A payment may be reversed if the transaction could n

======================================================================
FILE: refunds.md
======================================================================
# Refund Support

## Refund Eligibility

Refund eligibility depends on the type of purchase and the applicable refund policy. Customers should contact support if they are unsure whether a purchase qualifies for a refund.

## Request a Refund

Customers who want to request a refund should contact customer support and provide the relevant order or transaction details.

Support will review the request and determine whether the transaction qualifies for a refund.

## Refund Processing

After a refund is approved, the processing time may depend on the payment method and financial institution.

Customers should allow the required processing time before contacting support about a missing refund.

## Refund Not Received

If a customer has been informed that a refund was processed but the amount has not appeared, they should check their payment account and allow the expected processing period.

If the refund is still missing after that period, they should contact support with the refund or tran

======================================================================
FILE: returns.md
======================================================================
# Returns Support

## Return Eligibility

Customers may be able to return eligible products according to the applicable return policy.

Return eligibility may depend on the product, purchase date, and condition of the item.

## Start a Return

Customers who want to return a product should contact customer support or use the available return process.

They should provide the relevant order information when requesting a return.

## Return Condition

Returned products may need to be in an acceptable condition and may need to include the original accessories or packaging.

Customers should review the applicable return requirements before sending an item back.

## Return Shipping

Return shipping instructions depend on the order and the applicable return policy.

Customers should follow the provided return instructions and use the recommended shipping method when required.

## Return Status

Customers can contact support to check the status of a return.

They should provide their order or r

======================================================================
FILE: technical_support.md
======================================================================
# Technical Support

## Internet Connection Problems

If a customer is experiencing internet connection problems, they should first check whether the issue affects only one device or multiple devices.

Customers can restart their network equipment and check that all cables and connections are secure.

If the problem continues, they should contact technical support with details about the issue.

## Slow Internet

Customers experiencing slow internet should check whether multiple devices are using the connection at the same time.

They can restart their network equipment and test the connection again.

If the connection remains slow, they should contact technical support.

## Connection Keeps Disconnecting

If the internet connection repeatedly disconnects, customers should restart their network equipment and check all physical connections.

If the disconnections continue, technical support may need additional information about the device, connection, and frequency of the problem.

## Ap

In [4]:
documents = []

for file in files:
    text = file.read_text(encoding="utf-8").strip()

    documents.append({
        "source": file.name,
        "text": text
    })

print(f"Loaded documents: {len(documents)}")
print()

for document in documents:
    print(document["source"], "→", len(document["text"]), "characters")

Loaded documents: 6

account.md → 1547 characters
billing.md → 1545 characters
payments.md → 1817 characters
refunds.md → 1631 characters
returns.md → 1692 characters
technical_support.md → 2453 characters

In [5]:
documents[0]

{'source': 'account.md',
 'text': '# Account Support\n\n## Creating an Account\n\nCustomers can create an account by providing their email address and choosing a secure password. The email address should be valid and accessible because it may be required for account verification.\n\n## Account Verification\n\nIf an account requires verification, customers should check their email for the verification message. They should also check their spam or junk folder if the message is not visible in the inbox.\n\n## Forgot Password\n\nCustomers who forget their password should use the password reset option on the sign-in page. A password reset link will be sent to the registered email address.\n\n## Password Reset Email Not Received\n\nIf the password reset email does not arrive, customers should check their spam or junk folder and confirm that they entered the correct email address. If the email is still not received, they should contact customer support.\n\n## Change Account Email\n\nCustomers who need to change the email associated with their account should contact customer support. Support may request account information to verify ownership before making the change.\n\n## Account Locked\n\nAn account may be temporarily locked after multiple unsuccessful login attempts. Customers should wait before trying again or contact customer support if they cannot regain access.\n\n## Close an Account\n\nCustomers who want to close their account should contact customer support. Account closure may be permanent, so customers should confirm that they no longer need the account before requesting closure.'}

In [6]:
lengths = [len(document["text"]) for document in documents]

print("Minimum characters:", min(lengths))
print("Maximum characters:", max(lengths))
print("Average characters:", sum(lengths) / len(lengths))

Minimum characters: 1545
Maximum characters: 2453
Average characters: 1780.8333333333333

In [8]:
document_summary = pd.DataFrame({
    "source": [document["source"] for document in documents],
    "characters": lengths
})

document_summary

                 source  characters
0            account.md        1547
1            billing.md        1545
2           payments.md        1817
3            refunds.md        1631
4            returns.md        1692
5  technical_support.md        2453

In [9]:
document_summary = document_summary.sort_values(
    "characters",
    ascending=False
).reset_index(drop=True)

document_summary

                 source  characters
0  technical_support.md        2453
1           payments.md        1817
2            returns.md        1692
3            refunds.md        1631
4            account.md        1547
5            billing.md        1545

In [10]:
print("Total documents:", len(documents))
print("Total characters:", sum(lengths))
print("Average document length:", round(sum(lengths) / len(lengths), 2))

Total documents: 6
Total characters: 10685
Average document length: 1780.83

In [14]:
document_summary.describe()

        characters
count     6.000000
mean   1780.833333
std     344.602041
min    1545.000000
25%    1568.000000
50%    1661.500000
75%    1785.750000
max    2453.000000