In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

retrieval_df = pd.read_csv(
    PROCESSED_DIR / "retrieval_test_results.csv"
)

print("Retrieval test cases:", len(retrieval_df))
retrieval_df

Retrieval test cases: 5

                                       query                source  similarity
0  I forgot my password. How can I reset it?            account.md    0.533033
1                I want to return a product.            returns.md    0.669366
2               How long does a refund take?            refunds.md    0.512385
3     My internet connection is not working.  technical_support.md    0.496682
4                   Why was I charged twice?            billing.md    0.523341

In [6]:
expected_sources = [
    "account.md",
    "returns.md",
    "refunds.md",
    "technical_support.md",
    "billing.md"
]

retrieval_df["expected_source"] = expected_sources

retrieval_df["correct"] = (
    retrieval_df["source"] == retrieval_df["expected_source"]
)

retrieval_df

,query,source,similarity,expected_source,correct
0,I forgot my password. How can I reset it?,account.md,0.533033,account.md,True
1,I want to return a product.,returns.md,0.669366,returns.md,True
2,How long does a refund take?,refunds.md,0.512385,refunds.md,True
3,My internet connection is not working.,technical_support.md,0.496682,technical_support.md,True
4,Why was I charged twice?,billing.md,0.523341,billing.md,True

In [7]:
retrieval_accuracy = retrieval_df["correct"].mean()

print(f"Retrieval Accuracy: {retrieval_accuracy:.2%}")

Retrieval Accuracy: 100.00%

In [8]:
evaluation_summary = {
    "total_questions": len(retrieval_df),
    "correct_retrievals": int(retrieval_df["correct"].sum()),
    "retrieval_accuracy": retrieval_accuracy
}

evaluation_summary

{'total_questions': 5,
 'correct_retrievals': 5,
 'retrieval_accuracy': np.float64(1.0)}

In [9]:
import json

evaluation_path = PROCESSED_DIR / "evaluation_summary.json"

with open(evaluation_path, "w", encoding="utf-8") as f:
    json.dump(evaluation_summary, f, indent=4)

print("Saved:", evaluation_path)

Saved: d:\ai-customer-support-assistant\data\processed\evaluation_summary.json

In [10]:
print("Final Retrieval Accuracy:", f"{retrieval_accuracy:.2%}")

Final Retrieval Accuracy: 100.00%